"""T008 — contract test for install-lock v3 (Spec 008 shape, renamed by Spec 013).

Assertions
- The three MVP shapes validate: minimal Spec-008 constitution-only shape, a
  Spec-008 full shape with molecules + participating_roots + visibility_marker +
  generation_inputs.
- Negative cases prove the schema tightens where Spec 008 needs it: molecule
  records without `source` are rejected, generation-input identities are unique
  and sorted, and retired integrity fields are rejected.
"""

from __future__ import annotations

import pytest

from haex_hive.schema import loader
from haex_hive.schema.validator import SchemaValidationError, validate

SCHEMA_NAME = "install-lock.v3.schema.json"

_GENERATION_ID = "g_20260831T142011Z_a4c2"


def _minimal_spec_008_shape() -> dict:
    """Build the minimal Spec 008 constitution-only install lock shape."""
    return {
        "haex_hive_version": "3",
        "generated_by": "haex 2.0.0",
        "constitution": {
            "sources": [
                {
                    "id": "com.example.publisher.constitution",
                    "revision": "0" * 40,
                    "source": "https://github.com/example/publisher",
                }
            ],
            "assembled_by": {"tool": "haex", "version": "2.0.0"},
        },
    }


def _spec_008_shape() -> dict:
    """Build a complete valid Spec 008 install lock shape."""
    base = _minimal_spec_008_shape()
    base["molecules"] = [
        {
            "id": "com.example.publisher.constitution",
            "source": "https://github.com/example/publisher",
            "revision": "0" * 40,
            "contributed_paths": [
                ".haex-hive/atoms/com.example.publisher.constitution/manifest.json"
            ],
        }
    ]
    base["participating_roots"] = [".haex-hive/"]
    base["visibility_marker"] = {
        "generation_id": _GENERATION_ID,
    }
    base["generation_inputs"] = [
        {
            "kind": "adapter",
            "id": "com.example.adapter",
            "revision": "git:" + "1" * 40,
            "serialization": {
                "format": "json",
                "encoding": "UTF-8",
                "newline": "LF",
                "key_order": "lexicographic-utf8",
                "indent": 2,
                "ensure_ascii": False,
            },
        }
    ]
    return base


def test_schema_loads() -> None:
    """Ensure the vendored install-lock schema is available."""
    schema = loader.load(SCHEMA_NAME)
    assert schema["title"].startswith("haex-hive Install Lockfile v3")


def test_minimal_spec_008_shape_validates() -> None:
    """Accept the constitution-only Spec 008 install lock shape."""
    validate(_minimal_spec_008_shape(), SCHEMA_NAME)


def test_full_spec_008_shape_validates() -> None:
    """Accept the complete Spec 008 install lock shape."""
    validate(_spec_008_shape(), SCHEMA_NAME)


def test_atom_missing_source_is_rejected() -> None:
    """Require a publisher source on every installed molecule record."""
    data = _spec_008_shape()
    del data["molecules"][0]["source"]
    with pytest.raises(SchemaValidationError):
        validate(data, SCHEMA_NAME)


def test_generation_input_requires_serialization_profile() -> None:
    """Require explicit canonical serialization settings for generated bytes."""
    data = _spec_008_shape()
    del data["generation_inputs"][0]["serialization"]
    with pytest.raises(SchemaValidationError):
        validate(data, SCHEMA_NAME)


def test_retired_content_integrity_is_rejected_in_constitution() -> None:
    """Reject retired output-integrity fields in the constitution block."""
    data = _minimal_spec_008_shape()
    data["constitution"]["content_integrity"] = "sha256-" + "A" * 43
    with pytest.raises(SchemaValidationError):
        validate(data, SCHEMA_NAME)


def test_retired_content_integrity_is_rejected_in_atom() -> None:
    """Reject retired output-integrity fields in molecule records."""
    data = _spec_008_shape()
    data["molecules"][0]["content_integrity"] = "sha256-" + "A" * 43
    with pytest.raises(SchemaValidationError):
        validate(data, SCHEMA_NAME)


def test_duplicate_participating_roots_are_rejected() -> None:
    """Reject repeated participating-root identities."""
    data = _spec_008_shape()
    data["participating_roots"].append(".haex-hive/")
    with pytest.raises(SchemaValidationError):
        validate(data, SCHEMA_NAME)


def test_duplicate_generation_input_identity_is_rejected() -> None:
    """Reject duplicate identities even when their revisions differ."""
    data = _spec_008_shape()
    duplicate = dict(data["generation_inputs"][0])
    duplicate["revision"] = "git:" + "2" * 40
    data["generation_inputs"].append(duplicate)
    with pytest.raises(SchemaValidationError):
        validate(data, SCHEMA_NAME)


def test_generation_inputs_must_be_sorted_by_kind_and_id() -> None:
    """Reject generation-input entries that are out of canonical order."""
    data = _spec_008_shape()
    data["generation_inputs"].insert(
        0,
        {
            "kind": "tool-config",
            "id": "com.example.config",
            "revision": "sha256:" + "2" * 64,
            "serialization": dict(data["generation_inputs"][0]["serialization"]),
        },
    )
    with pytest.raises(SchemaValidationError):
        validate(data, SCHEMA_NAME)


@pytest.mark.parametrize(
    ("format_name", "key_order", "indent", "ensure_ascii"),
    [
        ("json", "not-applicable", None, False),
        ("json", "lexicographic-utf8", 2, True),
        ("text", "lexicographic-utf8", None, False),
        ("text", "not-applicable", 2, False),
        ("text", "not-applicable", None, True),
        ("toml", "lexicographic-utf8", None, False),
        ("toml", "not-applicable", 2, False),
        ("toml", "not-applicable", None, True),
    ],
)
def test_serialization_profile_rejects_format_mismatch(
    format_name: str, key_order: str, indent: int | None, ensure_ascii: bool
) -> None:
    """Reject profiles whose fields describe a different serialization format."""
    data = _spec_008_shape()
    data["generation_inputs"][0]["serialization"] = {
        "format": format_name,
        "encoding": "UTF-8",
        "newline": "LF",
        "key_order": key_order,
        "indent": indent,
        "ensure_ascii": ensure_ascii,
    }
    with pytest.raises(SchemaValidationError):
        validate(data, SCHEMA_NAME)


@pytest.mark.parametrize(
    "format_name",
    ["json", "text", "toml"],
)
def test_serialization_profile_accepts_format_specific_shape(format_name: str) -> None:
    """Accept the canonical profile shape for every supported format."""
    data = _spec_008_shape()
    data["generation_inputs"][0]["serialization"] = {
        "format": format_name,
        "encoding": "UTF-8",
        "newline": "LF",
        "key_order": "lexicographic-utf8" if format_name == "json" else "not-applicable",
        "indent": 2 if format_name == "json" else None,
        "ensure_ascii": False,
    }
    validate(data, SCHEMA_NAME)


def test_invalid_atom_source_uri_is_rejected() -> None:
    """Reject malformed molecule source URIs."""
    data = _spec_008_shape()
    data["molecules"][0]["source"] = "http://[invalid"
    with pytest.raises(SchemaValidationError):
        validate(data, SCHEMA_NAME)
